// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Fetch = require("bs-fetch/src/Fetch.js");
var Belt_Option = require("bs-platform/lib/js/belt_Option.js");
var Caml_option = require("bs-platform/lib/js/caml_option.js");

require('isomorphic-fetch')
;

var UnFetch = Fetch;

var gql = "https://json-placeholder-graphql.herokuapp.com/graphql";

var API = {
  rest: "https://jsonplaceholder.typicode.com/",
  gql: gql
};

var Raw = {};

var query = "query   {\nuser(id: 1)  {\nid  \nusername  \nemail  \nphone  \nwebsite  \n}\n\n}\n";

function parse(value) {
  var value$1 = value.user;
  var tmp;
  if (value$1 == null) {
    tmp = undefined;
  } else {
    var value$2 = value$1.id;
    var value$3 = value$1.username;
    var value$4 = value$1.email;
    var value$5 = value$1.phone;
    var value$6 = value$1.website;
    tmp = {
      id: !(value$2 == null) ? value$2 : undefined,
      username: !(value$3 == null) ? value$3 : undefined,
      email: !(value$4 == null) ? value$4 : undefined,
      phone: !(value$5 == null) ? value$5 : undefined,
      website: !(value$6 == null) ? value$6 : undefined
    };
  }
  return {
          user: tmp
        };
}

function serialize(value) {
  var value$1 = value.user;
  var user;
  if (value$1 !== undefined) {
    var value$2 = value$1.website;
    var website = value$2 !== undefined ? value$2 : null;
    var value$3 = value$1.phone;
    var phone = value$3 !== undefined ? value$3 : null;
    var value$4 = value$1.email;
    var email = value$4 !== undefined ? value$4 : null;
    var value$5 = value$1.username;
    var username = value$5 !== undefined ? value$5 : null;
    var value$6 = value$1.id;
    var id = value$6 !== undefined ? value$6 : null;
    user = {
      id: id,
      username: username,
      email: email,
      phone: phone,
      website: website
    };
  } else {
    user = null;
  }
  return {
          user: user
        };
}

function serializeVariables(param) {
  
}

function makeVariables(param) {
  
}

function makeDefaultVariables(param) {
  
}

var Query = {
  Raw: Raw,
  query: query,
  parse: parse,
  serialize: serialize,
  serializeVariables: serializeVariables,
  makeVariables: makeVariables,
  makeDefaultVariables: makeDefaultVariables
};

function makeErrorJson(err) {
  var error = String(err);
  var json = {};
  json["error"] = error;
  return json;
}

function handleQuery(q) {
  return fetch(gql, Fetch.RequestInit.make(/* Post */2, {
                          "Content-Type": "application/graphql"
                        }, Caml_option.some(q), undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined)(undefined)).then(function (prim) {
                  return prim.json();
                }).then(function (response) {
                return Promise.resolve(response);
              }).catch(function (err) {
              var error = makeErrorJson(err);
              console.log("ERROR", error);
              return Promise.resolve(error);
            });
}

function handleData(data) {
  console.log("handleData");
  console.log("handleData", data);
  console.log(data.user);
  console.log(Caml_option.nullable_to_opt(data.user));
  var user = data.user;
  var id = !(user == null) ? user.id : undefined;
  console.log("id", id);
  
}

function handleQueryt(user) {
  console.log("-------------");
  console.log("handleQueryt:(user: Query.t):BEGIN");
  console.log("-------------");
  console.log("user: Query.t", user);
  var user$1 = user.user;
  if (user$1 !== undefined) {
    console.log("uzer()", user$1);
  } else {
    console.log("None");
  }
  var user$2 = user.user;
  var uzer = user$2 !== undefined ? user$2 : undefined;
  console.log("uzer", Caml_option.some(uzer));
  var user$3 = user.user;
  if (user$3 !== undefined) {
    console.log("userId()", user$3.id);
  } else {
    console.log("None");
  }
  var user$4 = user.user;
  var userId = user$4 !== undefined ? Caml_option.some(user$4.id) : undefined;
  console.log("userId", userId);
  var user$5 = user.user;
  var userName = user$5 !== undefined ? Caml_option.some(user$5.username) : undefined;
  console.log("userName", userName);
  console.log("Nulled", Belt_Option.getWithDefault(undefined, (user == null) ? undefined : Caml_option.some(user)));
  console.log("-------------");
  console.log("(user: Query.t):END");
  console.log("-------------");
  
}

function handleUser(user) {
  var user$1 = user.user;
  if (user$1 !== undefined) {
    console.log("uzer()", user$1);
  } else {
    console.log("None");
  }
  var user$2 = user.user;
  var uzer = user$2 !== undefined ? user$2 : undefined;
  console.log("uzer", Caml_option.some(uzer));
  var user$3 = user.user;
  if (user$3 !== undefined) {
    console.log("userId()", user$3.id);
  } else {
    console.log("None");
  }
  var user$4 = user.user;
  var userId = user$4 !== undefined ? Caml_option.some(user$4.id) : undefined;
  console.log("userId", userId);
  var user$5 = user.user;
  var userName = user$5 !== undefined ? Caml_option.some(user$5.username) : undefined;
  console.log("userName", userName);
  var user$6 = user.user;
  var user$7;
  if (user$6 !== undefined) {
    var user_id = user$6.id;
    var user_username = user$6.username;
    var user_email = user$6.email;
    var user_phone = user$6.phone;
    var user_website = user$6.website;
    var user$8 = {
      id: user_id,
      username: user_username,
      email: user_email,
      phone: user_phone,
      website: user_website
    };
    console.log("user.id in switch", user_id);
    user$7 = user$8;
  } else {
    user$7 = undefined;
  }
  console.log("user", user$7);
  console.log("Nulled", Belt_Option.getWithDefault(undefined, (user$7 == null) ? undefined : Caml_option.some(user$7)));
  console.log("-------------");
  console.log("(user: Query.t):END");
  console.log("-------------");
  
}

var parseQueryRaw = parse;

function parseJsonData(data) {
  return handleQueryt(parse(data));
}

var test = handleQuery(query).then(function (response) {
      return Promise.resolve(handleUser(parse(response.data)));
    });

function test2(response) {
  return response.then(function (data) {
              return Promise.resolve(handleQueryt(parse(data)));
            });
}

exports.UnFetch = UnFetch;
exports.API = API;
exports.Query = Query;
exports.makeErrorJson = makeErrorJson;
exports.handleQuery = handleQuery;
exports.handleData = handleData;
exports.handleQueryt = handleQueryt;
exports.handleUser = handleUser;
exports.parseQueryRaw = parseQueryRaw;
exports.parseJsonData = parseJsonData;
exports.test = test;
exports.test2 = test2;
/*  Not a pure module */
