// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Fetch = require("bs-fetch/src/Fetch.bs.js");

require('isomorphic-fetch')
;

var $$AbortController = Fetch.$$AbortController;

var HeadersInit = Fetch.HeadersInit;

var $$Headers = Fetch.$$Headers;

var BodyInit = Fetch.BodyInit;

var Body = Fetch.Body;

var RequestInit = Fetch.RequestInit;

var $$Request = Fetch.$$Request;

var $$Response = Fetch.$$Response;

var $$FormData = Fetch.$$FormData;

exports.$$AbortController = $$AbortController;
exports.HeadersInit = HeadersInit;
exports.$$Headers = $$Headers;
exports.BodyInit = BodyInit;
exports.Body = Body;
exports.RequestInit = RequestInit;
exports.$$Request = $$Request;
exports.$$Response = $$Response;
exports.$$FormData = $$FormData;
/*  Not a pure module */
